### ISSUE TITLE
`cids` should be a dependency, not a devDependency

### ISSUE THREAD

**Issue by rrthomas** [ipfs/js-ipfs-unixfs#118]
The module `cids` is required by `src/utils/persist.js`.

I found this problem because of hitting an error exactly like [this one](https://stackoverflow.com/questions/66236701/multihash-must-be-a-buffer-error-while-trying-to-upload-files-to-ipfs-using-ip), which was caused by an old version of `cids`, which is required by `web3`, happening to be the version in the top level of my project's `node_modules`.

Thanks for IPFS!

**Comment by achingbrain** [comment]
Nice spot, thanks for opening this.  It should be fixed in `ipfs-unixfs-importer@6.0.0` and above.  It'll get rolled into IPFS as part of https://github.com/ipfs/js-ipfs/pull/3550 and shipped in the next release.

**Comment by rrthomas** [comment]
Thanks for the quick fix, @achingbrain!
