### ISSUE TITLE
Align sharding threshold detection

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs-unixfs#149]
go-IPFS has taken a different approach to js-IPFS in deciding when to start using a HAMT shard instead of a regular directory.

js-IPFS has an arbitrary 1k entry limit, overridable by the user.

go-IPFS calculates the likely block size of the directory node, sharding once it increases above a certain size.

We should align with the go-IPFS calculation, in order to not have divergent hashes for a given directory.

Ref: https://github.com/ipfs/go-ipfs/issues/7022#issuecomment-832178501

**Comment by tinytb** [comment]
2022-11-22: still needs to be done; no time pressure.
