### ISSUE TITLE
`ipfs-unixfs-importer`:  `import` type declaration imports `UnixFS` from the wrong location

### ISSUE THREAD

**Issue by mistermoe** [ipfs/js-ipfs-unixfs#214]
## Summary
`ipfs-unixfs-importer`:  `import` type declaration imports `UnixFS` from the wrong location

## Impact
unable to use `ipfs-unixfs-importer` package in typescript projects. attempting to transpile typescript project using `tsc` fails with the following error:

```shell
> tsc

node_modules/ipfs-unixfs-importer/types/src/index.d.ts:26:20 - error TS2307: Cannot find module 'ipfs-unixfs/src' or its corresponding type declarations.

26     unixfs: import("ipfs-unixfs/src").UnixFS | undefined;
                      ~~~~~~~~~~~~~~~~~


Found 1 error.
```

## Potential Cause
- `typesVersions` in [`package.json`](https://github.com/ipfs/js-ipfs-unixfs/blob/master/packages/ipfs-unixfs/package.json#L23-L34) of `ipfs-unixfs` has a path mapping that checks both `types/*` and `types/src/*`. Removing `typesVersions` entirely and regenerating the type declarations yields `unixfs: import("ipfs-unixfs").UnixFS | undefined` which solves the problem because typescript resolves the type using the `types` property in `package.json`. Though, i'm not sure if this is the way we want to solve the problem. I'm not sure whether downstream projects are importing types that aren't exported from `index.d.ts`. I think ideally, using something like [`npm-dts`](https://github.com/vytenisu/npm-dts) to bundle all types into 1 `index.d.ts` that is made available at the root of the package tarball would remove a lot of complexity around configuring types 

## Somewhat related
- type declaration files are duplicated in the package
![image](https://user-images.githubusercontent.com/4887440/169102657-3748abb8-a59a-432c-a398-ae85e411af0a.png)
- I think that the [`reset`](https://github.com/ipfs/js-ipfs-unixfs/blob/master/package.json#L20)  npm script needs to delete the `types` directory in every package because it's auto-generated. not deleting them prevents types from being regenerated

**Comment by mistermoe** [comment]
@achingbrain Let me know if there's anything that i can help provide clarity on.

**Comment by mhchu-multiverse** [comment]
It looks like this was resolved by removing `typesVersions` from `package.json` in commit 465670eab2e707b14b14047e2da4ede23590196e but was reintroduced in commit 9fccb7c4bf989c052ba67ab2c9280273aecfda36. Between these two, there have been no published version, so there is currently no version I have found using `ipfs-unixfs-importer` which compiles with `tsc`.

**Comment by achingbrain** [comment]
`tsc` keeps choosing the wrong type when inferring return types.  I think the trick is to specify return types on exported functions, then you get what you expect, whereas when you let the compiler figure it out you frequently get weird frankentypes.
