### ISSUE TITLE
Mutable fs

### ISSUE THREAD

**Issue by linonetwo** [ipfs/js-ipfs-unixfs#22]
Seems after folder converted into protobuf, we can't add new files to it. So ipfs-unixfs is immutable.

Can we do something like docker's multi-level file system, to make ipfs-unixfs mutable?

**Comment by diasdavid** [comment]
There is indeed a thing called `Mutable File System` on go-ipfs. See:

- https://github.com/ipfs/go-ipfs/issues/1607
- https://github.com/ipfs/community/issues/214
- https://github.com/ipfs/specs/issues/98
- https://github.com/ipfs/specs/issues/174
