### ISSUE TITLE
Concurrent block get

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs-unixfs#236]
One thing I'm seeing in the unixfs exporter is single block gets over bitswap. Basically, I think that [this](https://github.com/ipfs/js-ipfs-unixfs/blob/de1a7f0afc144462b374919a44d3af4fae3a49da/packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.js#L69) is causing bitswap messages with only 1 block to be sent out since we're waiting for each one. I think we might be able to get a nice speed up if all the links (or a sensible subset) were requested from the blockstore (bitswap) concurrently.

**Comment by achingbrain** [comment]
Fixed by #249 and #286
