### ISSUE TITLE
Python/JS Implementation JSON sharding

### ISSUE THREAD

**Issue by jeamick** [ipfs/js-ipfs-unixfs#26]
Hello there ,

Is there a Python implementation of IPFS' unixfs (a Unix FileSystem representation on top of a MerkleDAG)?

Indeed I  am looking to do  JSON sharding with the ipfs python api

Is there an example of this in Javascript?

Thanks

Regards

**Comment by diasdavid** [comment]
https://github.com/ipfs/py-ipfs is still in its early days. You can get familiar with the DAG (Graph) API at https://github.com/ipfs/js-ipfs/tree/master/examples/traverse-ipld-graphs. Open a topic in http://discuss.ipfs.io/ if you get stuck :)
