### ISSUE TITLE
how to wraps the data in a merkle dag with xamarin forms or c#.?

### ISSUE THREAD

**Issue by mosinms7711** [ipfs/js-ipfs-unixfs#32]
How to wrap data in Merkle Dag with xamarin forms or c#.?I need to add content to ipfs network.Before that i want hash value for the content.Now i can get hash values of raw data but when we add content to ipfs it wrap the data with merkle dag then create hash value.

**Comment by richardschneider** [comment]
@mosinms7711 Please stop spamming.  This project is about JavaScript not C#.  

I've given you an [answer](https://github.com/richardschneider/net-ipfs-api/issues/44#issuecomment-435293464) in [net-ipfs-api](https://github.com/richardschneider/net-ipfs-api).
