### ISSUE TITLE
bug: rabin chunker errors when no options are passed

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-ipfs-unixfs#339]
calling `rabin()` throws an error, `Error: please specify an average chunk size`

https://github.com/ipfs/js-ipfs-unixfs/blob/b7a98f0e850bf488ba7430e90812ddb5f5c0c438/packages/ipfs-unixfs-importer/src/chunker/rabin.ts#L53-L55

options are all optional, and there is a default AVG chunk size, so we should not be erroring here, or we should have better enforced types.

**Comment by achingbrain** [comment]
Good spot, would you like to PR a quick fix?
