### ISSUE TITLE
onlyHash alternative?

### ISSUE THREAD

**Issue by buu700** [ipfs/js-ipfs-unixfs#342]
Is there an alternative to the [`onlyHash`](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsadddata-options) option from ipfs-core? Nothing in the `ImporterOptions` interface looks similar.

I wasn't sure which repository was more appropriate, so I submitted the same issue here: https://github.com/ipfs/helia-unixfs/issues/58

**Comment by achingbrain** [comment]
Duplicate of https://github.com/ipfs/helia-unixfs/issues/58#issuecomment-1650005880
