### ISSUE TITLE
Inconsistent behaviour of isAsyncIterable function between Chrome and Firefox

### ISSUE THREAD

**Issue by negamaxi** [ipfs/js-ipfs-unixfs#354]
This code works in Firefox 115.0 and throws error in Chrome 114.0:

```ts
const fileObject = Array.from(files).map((file) => ({
  path: file.name,
  content: file.stream(),
}));

for await (const cid of heliaFS.addAll(fileObject)) {
  console.log(cid);
}
```
The reason is in this function:

https://github.com/ipfs/js-ipfs-unixfs/blob/47218799b4c28b0a4b4dc5a71b9d981e5d803424/packages/ipfs-unixfs-importer/src/dag-builder/index.ts#L37-L39

It returns `true` in Firefox and `false` in Chrome for `file.stream()` result (instance of `ReadableStream`) passed as value of `fileObject.content`:

![изображение](https://github.com/ipfs/js-ipfs-unixfs/assets/16529171/68404fb8-e63a-46b7-93af-d64455c90df0)

![изображение](https://github.com/ipfs/js-ipfs-unixfs/assets/16529171/3cc527c4-2280-46ed-94b7-3ff92d278dc9)

**Comment by achingbrain** [comment]
This is annoying but also expected - please see the browser compatibility table on MDN - https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#browser_compatibility

Only node.js, deno and Firefox support iterating over ReadableStreams as AsyncIterators.

The relevant Chromium bug is [here](https://bugs.chromium.org/p/chromium/issues/detail?id=929585&q=ReadableStream%20AsyncIterator&can=2)
