### ISSUE TITLE
many ppl can't install jsipfs because they didn't install git

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs-unixfs#45]
because `rabin-wasm` use `assemblyscript` from git

https://github.com/hugomrdias/rabin-wasm/blob/7575ed05fd3f4091813601130a685d372a18f7fc/package.json#L32-L35

```json
  },
  "dependencies": {
    "assemblyscript": "github:assemblyscript/assemblyscript#v0.6",
    "bl": "^1.0.0",
```

i have also test use `"assemblyscript": "^0.9.2"` replace

it not have any issue

but rabin-wasm author looks like didn't update now

so i hope can fix from `ipfs-unixfs-importer`

**Comment by achingbrain** [comment]
Can you open an issue on rabin-wasm please? I’m sure @hugomrdias will fix it.

**Comment by bluelovers** [comment]
already opened at last month, but no any reply
https://github.com/hugomrdias/rabin-wasm/issues/8

**Comment by MaxGraey** [comment]
[This PR](https://github.com/hugomrdias/rabin-wasm/pull/7) btw fixes this and also add many other improvements but maintained irresponsible unfortunately
