### ISSUE TITLE
Library cannot be used in a browser environment

### ISSUE THREAD

**Issue by bgrieder** [ipfs/js-ipfs-unixfs#5]
This is in reference to https://github.com/ipfs/js-ipfs/pull/104

The lib reads the protobuf schema from the FS which prevents from using it in a browser environment

    const protobuf = require('protocol-buffers')
    const schema = fs.readFileSync(path.resolve(__dirname, 'unixfs.proto'))

This prevents adding a `Buffer` from the browser into the Merkle DAG

**Comment by bgrieder** [comment]
Should we use this ? https://github.com/brianchirls/proto-loader

**Comment by diasdavid** [comment]
I've updated and released 0.1.2. Tests work in Node.js and in the browser and it makes the module available using the new pipeline. Let me know if you still have problems

@nginnever let's update js-ipfs and js-ipfs-data-importing to use the latest of js-ipfs-unixfs :)
