### ISSUE TITLE
Migrate relevant types from ipfs repo to this repo

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs-unixfs#94]
As per discussion here https://github.com/ipfs/js-ipfs/pull/3365/files/fa7c2c13c43bab922052104fe8aff863d9725e9b?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.ts#r520397622 there are bunch of type definitions that belong here instead of in js-ipfs repo.

We should migrate them here.

**Comment by achingbrain** [comment]
This module has types now so any consumers of this module should use the types exported by it.
